# Generated by Django 4.0.4 on 2022-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decription',
            field=models.TextField(default='TEST DESCRIPTION'),
        ),
    ]
