# Generated by Django 4.0.4 on 2022-05-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_quantity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oredered',
            new_name='ordered',
        ),
    ]
